# Generated by Django 2.1.2 on 2018-11-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_link', models.URLField(unique=True)),
                ('template_title', models.CharField(default='template', max_length=20)),
                ('template_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('document_link', models.URLField()),
                ('document_title', models.CharField(default='New Document', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('project_description', models.TextField(default='')),
                ('project_link', models.URLField(unique=True)),
                ('project_chat_link', models.URLField(default='')),
                ('calendar_api_token', models.CharField(blank=True, default='', max_length=100)),
                ('calendar_api_key', models.CharField(blank=True, default='', max_length=100)),
                ('git_api_key', models.CharField(blank=True, default='', max_length=100)),
                ('slack_api_key', models.CharField(blank=True, default='', max_length=100)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='api.Profile')),
                ('users', models.ManyToManyField(related_name='users', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.IntegerField()),
                ('subtask_title', models.CharField(blank=True, default='', max_length=100)),
                ('subtask_description', models.TextField()),
                ('subtask_status', models.CharField(choices=[('work_in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('finished', 'Completed'), ('not_feasible', 'Not Feasible')], default='Not Allocated', max_length=100)),
                ('issue_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubtaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublog_id', models.IntegerField()),
                ('subtask_deadline', models.DateField()),
                ('work_description', models.TextField()),
                ('is_finished', models.BooleanField()),
                ('submission_link', models.URLField(blank=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subtask')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_title', models.CharField(blank=True, default='', max_length=100)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('work_in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('finished', 'Completed'), ('not_feasible', 'Not Feasible')], default='Not Allocated', max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='document',
            name='template_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_id', 'project_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subtasklog',
            unique_together={('subtask_id', 'sublog_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('subtask_id', 'task_id')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('document_id', 'project_id')},
        ),
    ]
