# Generated by Django 2.1.1 on 2018-09-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('template_link', models.URLField(primary_key=True, serialize=False)),
                ('template_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('document_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('project_description', models.TextField()),
                ('project_link', models.URLField(unique=True)),
                ('project_chat_link', models.URLField(unique=True)),
                ('calendar_api_token', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('calendar_api_key', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('git_api_key', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('slack_api_key', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_id', models.CharField(blank=True, default='', max_length=100)),
                ('subtask_title', models.CharField(blank=True, default='', max_length=100)),
                ('subtask_description', models.TextField()),
                ('subtask_status', models.CharField(choices=[('work_in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('finished', 'Completed'), ('not_feasible', 'Not Feasible')], default='Not Allocated', max_length=100)),
                ('issue_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubtaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_deadline', models.DateField()),
                ('work_description', models.TextField()),
                ('is_finished', models.BooleanField()),
                ('submission_link', models.URLField(unique=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subtask')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('task_title', models.CharField(blank=True, default='', max_length=100)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('work_in_progress', 'In Progress'), ('unallocated', 'Unallocated'), ('finished', 'Completed'), ('not_feasible', 'Not Feasible')], default='Not Allocated', max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
        migrations.AddField(
            model_name='documents',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='documents',
            name='template_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType'),
        ),
        migrations.AlterUniqueTogether(
            name='subtasklog',
            unique_together={('subtask_id', 'assigned_user', 'subtask_deadline')},
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('subtask_id', 'task_id')},
        ),
    ]
