# Generated by Django 2.1.1 on 2018-10-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasklog',
            name='sublog_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subtasklog',
            unique_together={('subtask_id', 'sublog_id')},
        ),
    ]
