# Generated by Django 2.1.1 on 2018-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180925_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='template_title',
            field=models.CharField(default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='documents',
            name='document_title',
            field=models.CharField(default='New Document', max_length=20),
        ),
    ]
