# Generated by Django 2.1.3 on 2018-11-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
