# Generated by Django 2.1 on 2018-10-20 18:07
from django.db import migrations, models
from django.utils.text import slugify


def gen_slug(apps, schema_editor):
    MyProject = apps.get_model('api', 'Project')
    for row in MyProject.objects.all():
        row.slug = slugify(row.project_name)
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
