# Generated by Django 2.1.1 on 2018-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180925_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasklog',
            name='submission_link',
            field=models.URLField(null=True, unique=True),
        ),
    ]
