# Generated by Django 2.1 on 2018-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180925_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.AlterField(
            model_name='subtasklog',
            name='submission_link',
            field=models.URLField(blank=True),
        ),
    ]
