# Generated by Django 2.1.2 on 2018-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181020_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_chat_link',
            field=models.URLField(null=True, unique=True),
        ),
    ]
