# Generated by Django 2.1.2 on 2018-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181025_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_chat_link',
            field=models.URLField(default='', unique=True),
        ),
    ]
