// API Constants
export const API_URL = 'http://127.0.0.1:8000';
export const GITHUB_API_URL = 'https://api.github.com';

// Actions listed below

// Projects Actions
export const projectActions = {
  FETCH_USER_PROJECT_FAILED: 'FETCH_USER_PROJECT_FAILED',
  FETCH_USER_PROJECT_DONE: 'FETCH_USER_PROJECT_DONE',
  FETCH_USER_PROJECT_LOADING: 'FETCH_USER_PROJECT_LOADING',
  SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
  CREATE_NEW_PROJECT_SUCCESS: 'CREATE_NEW_PROJECT_SUCCESS',
  CREATING_NEW_PROJECT: 'CREATING_NEW_PROJECT',
  CREATE_NEW_PROJECT_FAILED: 'CREATE_NEW_PROJECT_FAILED',
};

export const githubActions = {
  FETCH_CONTRIBUTION_SUCCESS: 'FETCH_CONTRIBUTION_SUCCESS',
  FETCH_CONTRIBUTION_LOADING: 'FETCH_CONTRIBUTION_LOADING',
  FETCH_CONTRIBUTION_FAILED: 'FETCH_CONTRIBUTION_FAILED',
};

export const taskActions = {
  FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
  FETCH_TASKS_FAILED: 'FETCH_TASKS_FAILED',
  FETCH_TASKS_LOADING: 'FETCH_TASKS_LOADING',
  TASK_POST_SUCCESS: 'TASK_POST_SUCCESS',
  TASK_POST_FAILED: 'TASK_POST_FAILED',
  TASK_POSTING: 'TASK_POSTING',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',
};

export const documentActions = {
  FETCH_DOCS_SUCCESS: 'FETCH_DOCS_SUCCESS',
  FETCH_DOCS_FAILED: 'FETCH_DOCS_FAILED',
  DOCUMENT_POST_SUCCESS: 'DOCUMENT_POST_SUCCESS',
  DOCUMENT_POST_FAILED: 'DOCUMENT_POST_FAILED',
  DOCUMENT_POSTING: 'DOCUMENT_POSTING',
  DOCUMENT_DELETE_SUCCESS: 'DOCUMENT_DELETE_SUCCESS',
  DOCUMENT_DELETE_FAILED: 'DOCUMENT_DELETE_FAILED',
};

export const authActions = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
};

export const profileActions = {
  PROFILE_FETCH_SUCCESS: 'PROFILE_FETCH_SUCCESS',
  PROFILE_FETCH_FAILURE: 'PROFILE_FETCH_FAILURE',
};
